# Site settings
title: Brandon Space
name: www.thinktouch.net # your name
email: bo.wang@nottingham.ac.uk # your email address
description: >
    This personal site aims to share my knowledge. # this means to ignore newlines until "baseurl:"
baseurl: "http://www.thinktouch.net" # the subpath of your site, e.g. /blog
url: "http://www.thinktouch.net/" # the base hostname & protocol for your site
twitter_username: brandon_wangbo # your Twitter username
github_username:  BeRANDON # your Github username
disqus_username:  # your disqus username

google-analytics:  # add it if you have one

skillstree: true # turn on or off the skills tree in about page
finishedBooks: true

# Build settings
permalink: none
markdown: kramdown
